# Generated by Django 2.2.3 on 2019-08-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_acceso',
            field=models.IntegerField(choices=[(0, 'restringido'), (1, 'simple'), (2, 'asistenteR_H'), (3, 'jefeR_H'), (4, 'licencias'), (5, 'asistenteA_L'), (6, 'jefeA_L'), (7, 'vice_adm'), (8, 'vice_doc')], default=1),
        ),
    ]
