# Generated by Django 2.2.6 on 2019-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191025_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_acceso',
            field=models.IntegerField(choices=[(1, 'simple'), (2, 'asistente_OAGHDP'), (3, 'asistente2_OAGHDP'), (4, 'jefe_OAGHDP'), (5, 'abogado_AL'), (6, 'vacaciones_AL'), (7, 'jefe_AL'), (8, 'seleccion'), (9, 'planeacion'), (10, 'vice_doc'), (11, 'vice_adm'), (12, 'comunicacion_AL')], default=1),
        ),
    ]
