# Generated by Django 2.2.3 on 2019-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0003_solicitud_nombre_del_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asiste_en_calidad',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Asistente'), (2, 'Ponente'), (3, 'Conferencista'), (4, 'Otro')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='convenio',
            field=models.FileField(blank=True, null=True, upload_to='agreement/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reservas_personal',
            field=models.ManyToManyField(blank=True, null=True, to='situacionesadms.Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_del_evento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='soportes',
            field=models.FileField(blank=True, null=True, upload_to='attached/%Y/%m/%D/'),
        ),
    ]
