# Generated by Django 2.2.3 on 2019-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0005_auto_20190828_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='dias_pendientes1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días pendientes'),
        ),
    ]
