# Generated by Django 2.2.3 on 2019-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0006_solicitud_dias_pendientes1'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='va_a_vice',
            field=models.PositiveIntegerField(choices=[(0, 'sin destino'), (1, 'Docencia'), (2, 'Administrativa')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Describa su solicitud', null=True, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_dias_a_disfrutar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. días a disfrutar'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_dias_a_reservar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. días a reservar'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. reserva personal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resolucion_vaciones',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. resolución Vacaciones'),
        ),
    ]
