# Generated by Django 2.2.3 on 2019-09-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0007_auto_20190828_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='revisar_encargo',
        ),
    ]
