# Generated by Django 2.2.3 on 2019-09-04 16:01

import django.core.validators
from django.db import migrations, models
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0008_remove_solicitud_revisar_encargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='convenio',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='agreement/%Y', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='justificacion',
            field=models.TextField(blank=True, help_text='<em>Describa su solicitud</em>', null=True, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_rectoria',
            field=models.CharField(blank=True, help_text='<em>¿la reserva es por resolución?</em>', max_length=20, null=True, verbose_name='No. reserva rectoría'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reservas_personal',
            field=models.ManyToManyField(blank=True, to='situacionesadms.Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='soportes',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=situacionesadms.funciones_extra.update_filename, validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
