# Generated by Django 2.2.3 on 2019-09-10 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0009_auto_20190904_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='apellido_encargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Funcionario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='convenio',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=functools.partial(situacionesadms.funciones_extra.update_filename, *(), **{'path': 'agreement/%Y'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Empleado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_encargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Funcionario'),
        ),
    ]
