# Generated by Django 2.2.3 on 2019-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0011_auto_20190917_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='modifica_a1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modifica a'),
        ),
    ]
