# Generated by Django 2.2.3 on 2019-09-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0012_auto_20190917_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='modifica_a1',
        ),
    ]
