# Generated by Django 2.2.3 on 2019-09-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0013_remove_solicitud_modifica_a1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='modifica_a2',
        ),
    ]
