# Generated by Django 2.2.3 on 2019-09-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0014_remove_solicitud_modifica_a2'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='modifica_a1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modifica a'),
        ),
    ]
