# Generated by Django 2.2.3 on 2019-09-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0015_solicitud_modifica_a1'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='modifica_a2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacionesadms.Solicitud'),
        ),
    ]
