# Generated by Django 2.2.3 on 2019-09-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0016_solicitud_modifica_a2'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fue_modificada',
            field=models.BooleanField(default=False),
        ),
    ]
