# Generated by Django 2.2.3 on 2019-09-30 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0017_solicitud_fue_modificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='situacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacionesadms.SituacionAdministrativa'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='soportes',
            field=models.FileField(blank=True, null=True, upload_to=situacionesadms.funciones_extra.update_filename, validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
