# Generated by Django 2.2.3 on 2019-09-30 21:03

import django.core.validators
from django.db import migrations, models
import functools
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0019_auto_20190930_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='convenio',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(situacionesadms.funciones_extra.update_filename, *(), **{'path': 'agreement/%Y'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
