# Generated by Django 2.2.3 on 2019-10-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0021_auto_20191002_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='resolucion_viatico',
            new_name='resolucion_viaticos',
        ),
    ]
