# Generated by Django 2.2.3 on 2019-10-11 20:04

import django.core.validators
from django.db import migrations, models
import functools
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0022_auto_20191002_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asiste_en_calidad',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Asistente'), (2, 'Ponente'), (3, 'Conferencista'), (4, 'Otro')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='soportes',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(situacionesadms.funciones_extra.update_filename, *(), **{'path': 'attached/%Y'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
