# Generated by Django 2.2.3 on 2019-10-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0024_auto_20191011_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='fecha_modificaion',
            new_name='fecha_modificacion',
        ),
    ]
