# Generated by Django 2.2.3 on 2019-10-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0025_auto_20191011_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='va_a_vice',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'sin destino'), (1, 'Docencia'), (2, 'Administrativa')], null=True),
        ),
    ]
