# Generated by Django 2.2.3 on 2019-10-16 14:28

import django.core.validators
from django.db import migrations, models
import functools
import situacionesadms.funciones_extra


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0026_auto_20191011_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerechazo',
            name='motivo',
            field=models.TextField(help_text='Describa las razones por las cual se rechaza'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='convenio',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(situacionesadms.funciones_extra.update_filename, *(), **{'path': 'agreement'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_personal',
            field=models.CharField(blank=True, help_text='<em>¿La reserva la solicitó usted?</em>', max_length=50, null=True, verbose_name='No. reserva personal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_rectoria',
            field=models.CharField(blank=True, help_text='<em>¿la reserva viene de Rectoría?</em>', max_length=20, null=True, verbose_name='No. reserva rectoría'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='soportes',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(situacionesadms.funciones_extra.update_filename, *(), **{'path': 'attached'}), validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])]),
        ),
    ]
