# Generated by Django 2.2.3 on 2019-10-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0028_auto_20191018_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerechazo',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situacionesadms.Solicitud'),
        ),
    ]
