# Generated by Django 2.2.3 on 2019-10-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0029_auto_20191021_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='solicitud',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='situacionesadms.Solicitud'),
        ),
    ]
