# Generated by Django 2.2.3 on 2019-10-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0030_auto_20191021_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='modifica_a1',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='extiende_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extiende', to='situacionesadms.Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(0, 'Solicitud'), (1, 'Modificación'), (1, 'Corrección')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='modifica_a2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacionesadms.Solicitud'),
        ),
    ]
