# Generated by Django 2.2.3 on 2019-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0031_auto_20191021_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='modifica_a2',
            new_name='modifica_a',
        ),
    ]
