# Generated by Django 2.2.3 on 2019-10-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0032_auto_20191021_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='extiende_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extiende', to='situacionesadms.Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='modifica_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacionesadms.Solicitud'),
        ),
    ]
