# Generated by Django 2.2.3 on 2019-10-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0033_auto_20191022_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'papelera'), (1, 'tramite'), (2, 'corregida_modificada'), (3, 'aprobada'), (4, 'revocada'), (5, 'rechazada')], default=1),
        ),
    ]
