# Generated by Django 2.2.3 on 2019-10-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0034_auto_20191022_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='funcionario_encargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Empleado'),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='situacionesadms.Solicitud'),
        ),
        migrations.CreateModel(
            name='CartaEstemporaneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redaccion', models.TextField()),
                ('reintegro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situacionesadms.Reintegro')),
            ],
        ),
    ]
