# Generated by Django 2.2.3 on 2019-10-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0035_auto_20191025_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='check_asistente_RH',
            new_name='check_asistente_OAGHDP',
        ),
    ]
