# Generated by Django 2.2.3 on 2019-10-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0036_auto_20191025_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='check_asistente2_RH',
            new_name='check_asistente2_OAGHDP',
        ),
    ]
