# Generated by Django 2.2.6 on 2019-10-29 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('situacionesadms', '0039_auto_20191025_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaestemporaneo',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallerechazo',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reintegro',
            name='check_asistente_OAGHDP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reintegro',
            name='check_jefe_OAGHDP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ultimo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
