# Generated by Django 2.2.6 on 2019-10-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0040_auto_20191029_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='requiere_reintegro',
            field=models.BooleanField(default=True),
        ),
    ]
