# Generated by Django 2.2.6 on 2019-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0041_solicitud_requiere_reintegro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='no_reservas_personal',
            new_name='no_reserva_previa',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requiere_reintegro',
            field=models.BooleanField(default=False),
        ),
    ]
