# Generated by Django 2.2.7 on 2019-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0042_auto_20191030_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='revisar_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
