# Generated by Django 2.2.7 on 2019-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0044_auto_20191209_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegro',
            name='seguimiento',
            field=models.PositiveIntegerField(choices=[(0, 'papelera'), (1, 'trámite'), (2, 'corregida_modificada'), (3, 'aprobada'), (4, 'revocada'), (5, 'rechazada')], default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'papelera'), (1, 'trámite'), (2, 'corregida_modificada'), (3, 'aprobada'), (4, 'revocada'), (5, 'rechazada')], default=1),
        ),
    ]
