# Generated by Django 2.2.7 on 2019-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0045_auto_20191209_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='periodo',
            field=models.PositiveIntegerField(choices=[(0, 'todo el día'), (1, 'mañana'), (2, 'tarde')], default=0),
        ),
    ]
