# Generated by Django 2.2.7 on 2019-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0046_solicitud_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reintegro',
            name='pendiente_cumplido',
            field=models.BooleanField(default=False),
        ),
    ]
