# Generated by Django 2.2.7 on 2019-12-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0047_reintegro_pendiente_cumplido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegro',
            name='cumplido',
            field=models.FileField(blank=True, null=True, upload_to='cumplidos'),
        ),
        migrations.AlterField(
            model_name='reintegro',
            name='situacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='situacionesadms.Solicitud'),
        ),
    ]
