# Generated by Django 2.2.7 on 2019-12-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0048_auto_20191211_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegro',
            name='situacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='situacionesadms.Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='justificacion',
            field=models.TextField(blank=True, help_text='<em class="text-secondary">Describa su solicitud</em>', null=True, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_personal',
            field=models.CharField(blank=True, help_text='<em class="text-secondary">¿La reserva la solicitó usted?</em>', max_length=50, null=True, verbose_name='No. reserva personal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_rectoria',
            field=models.CharField(blank=True, help_text='<em class="text-secondary">¿la reserva viene de Rectoría?</em>', max_length=20, null=True, verbose_name='No. reserva rectoría'),
        ),
    ]
