# Generated by Django 2.2.7 on 2019-12-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0049_auto_20191213_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. reserva personal'),
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='no_reserva_previa',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='no_reserva_previa',
            field=models.CharField(blank=True, help_text='<em class="text-secondary">¿La reserva la solicitó usted?</em>', max_length=50, null=True, verbose_name='No. reserva previa o resolución'),
        ),
    ]
