# Generated by Django 2.2.7 on 2019-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0051_solicitud_fecha_acto_administrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_rectoria',
            field=models.CharField(blank=True, help_text='<em class="text-secondary">¿la reserva viene de Rectoría?</em>', max_length=20, null=True, verbose_name='No. reserva Rectoría'),
        ),
    ]
