# Generated by Django 2.2.7 on 2019-12-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacionesadms', '0053_auto_20191218_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='no_reserva_rectoria',
            field=models.CharField(blank=True, help_text='<em class="text-secondary">¿la reserva viene de Rectoría?</em>', max_length=50, null=True, verbose_name='No. reserva Resolución Rectoría'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='resolucion_vaciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. resolución Vacaciones'),
        ),
    ]
